FitnessClub/Controllers/Admin/AdminDashboardController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using FitnessClub.Data.Entities;
using System.ComponentModel.DataAnnotations;

namespace FitnessClub.Controllers.Admin
{
    [Authorize(Roles = "Admin")]
    public class AdminDashboardController : Controller
    {
        private readonly UserManager<ProjectUser> _userManager;
        private readonly SignInManager<ProjectUser> _signInManager;
        private readonly RoleManager<IdentityRole> _roleManager;

        public AdminDashboardController(
            UserManager<ProjectUser> userManager,
            SignInManager<ProjectUser> signInManager,
            RoleManager<IdentityRole> roleManager
    )
        {
            _userManager = userManager;
            _signInManager = signInManager;
            _roleManager = roleManager;
        }

        public async Task<IActionResult> Index()
        {
            var currentUser = await _userManager.GetUserAsync(User);
            ViewData["CurrentUserName"] = currentUser.UserName;
            ViewData["CurrentUserAvatar"] = currentUser.Avatar;
            return View("~/Views/Admin/Index.cshtml");
        }
    }
}

FitnessClub/Controllers/SportsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FitnessClub.Data;
using FitnessClub.Data.Entities;
using Microsoft.AspNetCore.Authorization;

namespace FitnessClub.Controllers
{
    [Authorize(Roles ="Admin")]
    public class SportsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public SportsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Sports
        public async Task<IActionResult> Index()
        {
            return View(await _context.Sports.ToListAsync());
        }

        // GET: Sports/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var sport = await _context.Sports
                .FirstOrDefaultAsync(m => m.Id == id);
            if (sport == null)
            {
                return NotFound();
            }

            return View(sport);
        }

        // GET: Sports/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Sports/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name")] Sport sport)
        {
            if (ModelState.IsValid)
            {
                _context.Add(sport);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(sport);
        }

        // GET: Sports/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var sport = await _context.Sports.FindAsync(id);
            if (sport == null)
            {
                return NotFound();
            }
            return View(sport);
        }

        // POST: Sports/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name")] Sport sport)
        {
            if (id != sport.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(sport);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SportExists(sport.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(sport);
        }

        // GET: Sports/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var sport = await _context.Sports
                .FirstOrDefaultAsync(m => m.Id == id);
            if (sport == null)
            {
                return NotFound();
            }

            return View(sport);
        }

        // POST: Sports/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var sport = await _context.Sports.FindAsync(id);
            _context.Sports.Remove(sport);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool SportExists(int id)
        {
            return _context.Sports.Any(e => e.Id == id);
        }
    }
}

FitnessClub/Controllers/TimesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FitnessClub.Data;
using FitnessClub.Data.Entities;
using Microsoft.AspNetCore.Authorization;

namespace FitnessClub.Controllers
{
    [Authorize(Roles = "Admin")]
    public class TimesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public TimesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Times
        public async Task<IActionResult> Index()
        {
            return View(await _context.Times.ToListAsync());
        }

        // GET: Times/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var time = await _context.Times
                .FirstOrDefaultAsync(m => m.Id == id);
            if (time == null)
            {
                return NotFound();
            }

            return View(time);
        }

        // GET: Times/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Times/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,DayTime")] Time time)
        {
            if (ModelState.IsValid)
            {
                _context.Add(time);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(time);
        }

        // GET: Times/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var time = await _context.Times.FindAsync(id);
            if (time == null)
            {
                return NotFound();
            }
            return View(time);
        }

        // POST: Times/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,DayTime")] Time time)
        {
            if (id != time.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(time);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TimeExists(time.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(time);
        }

        // GET: Times/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var time = await _context.Times
                .FirstOrDefaultAsync(m => m.Id == id);
            if (time == null)
            {
                return NotFound();
            }

            return View(time);
        }

        // POST: Times/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var time = await _context.Times.FindAsync(id);
            _context.Times.Remove(time);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TimeExists(int id)
        {
            return _context.Times.Any(e => e.Id == id);
        }
    }
}

FitnessClub/Controllers/TrainingsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FitnessClub.Data;
using FitnessClub.Data.Entities;
using Microsoft.AspNetCore.Authorization;

namespace FitnessClub.Controllers
{
    [Authorize(Roles = "Admin")]
    public class TrainingsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public TrainingsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Trainings
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Trainings.Include(t => t.Hall).Include(t => t.Sport).Include(t => t.TrainingType);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Trainings/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var training = await _context.Trainings
                .Include(t => t.Hall)
                .Include(t => t.Sport)
                .Include(t => t.TrainingType)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (training == null)
            {
                return NotFound();
            }

            return View(training);
        }

        // GET: Trainings/Create
        public IActionResult Create()
        {
            ViewData["HallId"] = new SelectList(_context.TrainingHalls, "Id", "Name");
            ViewData["SportId"] = new SelectList(_context.Sports, "Id", "Name");
            ViewData["TrainingTypeId"] = new SelectList(_context.TrainingTypes, "Id", "Name");
            return View();
        }

        // POST: Trainings/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,SportId,TrainerId,HallId,TrainingTypeId")] Training training)
        {
            if (ModelState.IsValid)
            {
                _context.Add(training);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["HallId"] = new SelectList(_context.TrainingHalls, "Id", "Name", training.HallId);
            ViewData["SportId"] = new SelectList(_context.Sports, "Id", "Name", training.SportId);
            ViewData["TrainingTypeId"] = new SelectList(_context.TrainingTypes, "Id", "Name", training.TrainingTypeId);
            return View(training);
        }

        // GET: Trainings/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var training = await _context.Trainings.FindAsync(id);
            if (training == null)
            {
                return NotFound();
            }
            ViewData["HallId"] = new SelectList(_context.TrainingHalls, "Id", "Name", training.HallId);
            ViewData["SportId"] = new SelectList(_context.Sports, "Id", "Name", training.SportId);
            ViewData["TrainingTypeId"] = new SelectList(_context.TrainingTypes, "Id", "Name", training.TrainingTypeId);
            return View(training);
        }

        // POST: Trainings/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,SportId,TrainerId,HallId,TrainingTypeId")] Training training)
        {
            if (id != training.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(training);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TrainingExists(training.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["HallId"] = new SelectList(_context.TrainingHalls, "Id", "Name", training.HallId);
            ViewData["SportId"] = new SelectList(_context.Sports, "Id", "Name", training.SportId);
            ViewData["TrainingTypeId"] = new SelectList(_context.TrainingTypes, "Id", "Name", training.TrainingTypeId);
            return View(training);
        }

        // GET: Trainings/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var training = await _context.Trainings
                .Include(t => t.Hall)
                .Include(t => t.Sport)
                .Include(t => t.TrainingType)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (training == null)
            {
                return NotFound();
            }

            return View(training);
        }

        // POST: Trainings/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var training = await _context.Trainings.FindAsync(id);
            _context.Trainings.Remove(training);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TrainingExists(int id)
        {
            return _context.Trainings.Any(e => e.Id == id);
        }
    }
}

FitnessClub/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FitnessClub</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">FitnessClub</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - FitnessClub - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

FitnessClub/Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="~/forAdminLayout/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/forAdminLayout/css/font-awesome.min.css" />
    <link rel="stylesheet" href="~/forAdminLayout/css/nprogress.css" />
    <link rel="stylesheet" href="~/forAdminLayout/css/green.css" />
    <link rel="stylesheet" href="~/forAdminLayout/css/bootstrap-progressbar-3.3.4.min.css" />
    <link rel="stylesheet" href="~/forAdminLayout/css/jqvmap.min.css" />
    <link rel="stylesheet" href="~/forAdminLayout/css/daterangepicker.css" />
    <link rel="stylesheet" href="~/forAdminLayout/css/custom.min.css" />

</head>
<body class="nav-md">
    <div class="container body">
        <div class="main_container">
            <div class="col-md-3 left_col">
                <div class="left_col scroll-view">
                    <div class="navbar nav_title" style="border: 0;">
                        <a asp-area="" asp-controller="AdminDashboard" asp-action="Index" class="site_title"><i class="fa fa-paw"></i> <span>AdminDashboard</span></a>
                    </div>

                    <div class="clearfix"></div>

                    <!-- menu profile quick info -->
                    <div class="profile clearfix">
                        <div class="profile_pic">
                            @{
                                if (ViewData["CurrentUserAvatar"] == null)
                                    ViewData["CurrentUserAvatar"] = "\\storage\\avatars\\unnamed.jpg";
                            }
                            <img src=@ViewData["CurrentUserAvatar"] alt="..." class="img-circle profile_img">
                        </div>
                        <div class="profile_info">
                            <span>Welcome,</span>
                            <h2>
                                @ViewData["CurrentUserName"]
                            </h2>
                        </div>
                    </div>
                    <!-- /menu profile quick info -->
                    <br />

                    <!-- sidebar menu -->
                    <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">

                        <div class="menu_section">                           
                            <ul class="nav side-menu">
                                <li>
                                    <a asp-area="" asp-controller="AdminDashboard" asp-action="Index"><i class="fa fa-home"></i> Home </a>
                                </li>
                                <li>
                                    <a asp-area="" asp-controller="Account" asp-action="Index"><i class="fa fa-home"></i> Users </a>
                                </li>
                                <li>
                                    <a asp-area="" asp-controller="Sports" asp-action="Index"><i class="fa fa-home"></i> Sports </a>
                                </li>
                                <li>
                                    <a asp-area="" asp-controller="TrainingHalls" asp-action="Index"><i class="fa fa-home"></i> Halls </a>
                                </li>
                                <li>
                                    <a asp-area="" asp-controller="TrainingTypes" asp-action="Index"><i class="fa fa-home"></i> TrainingTypes </a>
                                </li>
                                <li>
                                    <a asp-area="" asp-controller="Times" asp-action="Index"><i class="fa fa-home"></i> Times </a>
                                </li>
                                <li>
                                    <a asp-area="" asp-controller="Trainings" asp-action="Index"><i class="fa fa-home"></i> Trainings </a>
                                </li>
                            </ul>
                        </div>                      

                    </div>
                    <!-- /sidebar menu -->
                    <!-- /menu footer buttons -->
                    <div class="sidebar-footer hidden-small">
                        <a data-toggle="tooltip" data-placement="top" title="Profile">
                            <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
                        </a>

                        <a data-toggle="tooltip" data-placement="top" title="Logout" asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Action("Index", "Home", new { area = "" })">
                            <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
                        </a>
                    </div>
                    <!-- /menu footer buttons -->
                </div>
            </div>

            <!-- top navigation -->
            <div class="top_nav">
                <div class="nav_menu">
                    <div class="nav toggle">
                        <a id="menu_toggle"><i class="fa fa-bars"></i></a>
                    </div>
                    <nav class="nav navbar-nav" >                        
                    </nav>
                </div>
            </div>

            <div class="right_col" role="main">                
                    @RenderBody()
            </div>

            <footer>
                <div class="pull-right">
                    FitnessClub  - Make the impossible possible! 2021
                </div>
                <div class="clearfix"></div>
            </footer>
        </div>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/forAdminLayout/js/jquery.min.js"></script>
    <script src="~/forAdminLayout/js/bootstrap.bundle.min.js"></script>
    <script src="~/forAdminLayout/js/fastclick.js"></script>
    <script src="~/forAdminLayout/js/nprogress.js"></script>
    <script src="~/forAdminLayout/js/Chart.min.js"></script>
    <script src="~/forAdminLayout/js/gauge.min.js"></script>
    <script src="~/forAdminLayout/js/bootstrap-progressbar.min.js"></script>
    <script src="~/forAdminLayout/js/icheck.min.js"></script>
    <script src="~/forAdminLayout/js/skycons.js"></script>
    <script src="~/forAdminLayout/js/jquery.flot.js"></script>
    <script src="~/forAdminLayout/js/jquery.flot.pie.js"></script>
    <script src="~/forAdminLayout/js/jquery.flot.time.js"></script>
    <script src="~/forAdminLayout/js/jquery.flot.stack.js"></script>
    <script src="~/forAdminLayout/js/jquery.flot.resize.js"></script>
    <script src="~/forAdminLayout/js/jquery.flot.orderBars.js"></script>
    <script src="~/forAdminLayout/js/jquery.flot.spline.min.js"></script>
    <script src="~/forAdminLayout/js/curvedLines.js"></script>
    <script src="~/forAdminLayout/js/date.js"></script>
    <script src="~/forAdminLayout/js/jquery.vmap.js"></script>
    <script src="~/forAdminLayout/js/jquery.vmap.sampledata.js"></script>
    <script src="~/forAdminLayout/js/moment.min.js"></script>
    <script src="~/forAdminLayout/js/daterangepicker.js"></script>
    <script src="~/forAdminLayout/js/custom.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>